In [1]:
import tensorflow as tf
# a = 3
# Create a variable
w = tf.Variable([[0.5,1.0]])
x = tf.Variable([[2.0],[1.0]])
y = tf.matmul(w,x)

# variables have to be explicitly initialized before you can run ops 全局初始化
init_op = tf.global_variables_initializer()
# 在session区域进行计算
with tf.Session() as sess:
    sess.run(init_op)
    print(y.eval())

[[2.]]


In [ ]:
# float32
tf.zeros([3,4],int32) ==>[[0,0,0,0],[0,0,0,0],[0,0,0,0]]

# 'tensor' is [[1,2,3],[4,5,6]]
tf.zeros_like(tensor)  ==>[[0,0,0],[0,0,0]]
tf.ones([2,3],int32)  ==>[[1,1,1],[1,1,1]]

# tensor' is [[1,2,3],[4,5,6]]
tf.ones_like(tensor)  ==>[[1,1,1],[1,1,1]]

# Constant 1-D Tensor populated with value list
tensor = tf.constant([1,2,3,4,5,6,7]) ==> [1 2 3 4 5 6 7]

# Constant 2-D Tensor populated with value list
tensor = tf.constant(-1.0, shape=[2,3]) ==> [[-1. -1. -1.]
                                            [-1. -1. -1.]]

tf.linspace(10.0, 12.0, 3,name='linspace')  ==> [10.0 11.0 12.0]

# 'start' is 3
# 'limit' is 18
# 'delta' is 3
tf.range(start, limit, delta)  ==>[3,6,9,12,15]

In [2]:
norm = tf.random_normal([2,3], mean=-1, stddev=4)

# Shuffle the first dimension of a tensor
c = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(c)

# each time we run these ops, different results are generated
sess = tf.Session()
print(sess.run(norm))
print(sess.run(shuff))

[[-3.7609866 -7.6177645  2.343625 ]
 [-4.5016427 -3.9544795  1.8796103]]
[[1 2]
 [5 6]
 [3 4]]


In [3]:
state = tf.Variable(0)
new_value = tf.add(state, tf.constant(1))
update = tf.assign(state,new_value)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(state))
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


In [4]:
# tf.train.Saver
w = tf.Variable([[0.5, 1.0]])
x = tf.Variable([[2.0], [1.0]])
y = tf.matmul(w, x)
init_op = tf.global_variables_initializer()
saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(init_op)
# do some work with the model
#Save the variables to disk
    save_path = saver.save(sess,'C:\\Users\\sunfang\\Desktop\\tf')
    print('Model saved in file: ',save_path)

Model saved in file:  C:\Users\sunfang\Desktop\tf


In [7]:
import numpy as np
a = np.zeros((3,3))
ta = tf.convert_to_tensor(a)
with tf.Session() as sess:
    print(sess.run(ta))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)
output = tf.multiply(input1, input2)
with tf.Session() as sess:
    print(sess.run([output], feed_dict={input1:[7.0], input2:[2.0]}))

[array([14.], dtype=float32)]
